In [68]:
import pandas as pd

df = pd.read_csv('online_sales_dataset.csv')

In [69]:
#Inspection Data
print('\n------------Info--------------')
print(df.info())
print('\n------------Sample Data--------------')
display(df.sample(5))

------------Info--------------
<class 'pandas.DataFrame'>
RangeIndex: 49782 entries, 0 to 49781
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   InvoiceNo          49782 non-null  int64
 1   StockCode          49782 non-null  str
 2   Description        49782 non-null  str
 3   Quantity           49782 non-null  int64
 4   InvoiceDate        49782 non-null  str
 5   UnitPrice          49782 non-null  float64
 6   CustomerID         44804 non-null  float64
 7   Country            49782 non-null  str
 8   Discount           49782 non-null  float64
 9   PaymentMethod      49782 non-null  str
 10  ShippingCost       47293 non-null  float64
 11  Category           49782 non-null  str
 12  SalesChannel       49782 non-null  str
 13  ReturnStatus       49782 non-null  str
 14  ShipmentProvider   49782 non-null  str
 15  WarehouseLocation  46297 non-null  str
 16  OrderPriority      49782 non-null  str
dtypes: float64(4), int64(2), str(11)
memory usage: 6.5 MB
None

------------Sample Data--------------

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
48575,200041,SKU_1761,Headphones,22,2025-07-16 23:00,1.16,41906.0,Spain,0.15,paypall,24.38,Furniture,Online,Not Returned,UPS,Rome,Medium
15996,409642,SKU_1133,Desk Lamp,36,2021-10-28 12:00,87.75,63967.0,Germany,0.45,Credit Card,16.06,Furniture,Online,Not Returned,UPS,Paris,Low
42111,699165,SKU_1266,Wireless Mouse,29,2024-10-20 15:00,26.84,56797.0,Italy,0.23,paypall,7.75,Furniture,In-store,Not Returned,UPS,Berlin,Low
9215,240021,SKU_1141,USB Cable,47,2021-01-18 23:00,82.80,57627.0,Spain,0.26,Credit Card,6.77,Accessories,In-store,Not Returned,Royal Mail,Paris,Low
42074,229228,SKU_1056,Wireless Mouse,42,2024-10-19 02:00,37.62,36294.0,Australia,0.09,paypall,11.29,Accessories,In-store,Not Returned,DHL,London,Low

In [70]:
#  Check Duplicated Data
print(df.duplicated().sum())
print(df[df.duplicated()]  )

0
Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country, Discount, PaymentMethod, ShippingCost, Category, SalesChannel, ReturnStatus, ShipmentProvider, WarehouseLocation, OrderPriority]
Index: []

In [71]:
# Change Data Types
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors='coerce')
df.dtypes

InvoiceNo                     int64
StockCode                       str
Description                     str
Quantity                      int64
InvoiceDate          datetime64[us]
UnitPrice                   float64
CustomerID                  float64
Country                         str
Discount                    float64
PaymentMethod                   str
ShippingCost                float64
Category                        str
SalesChannel                    str
ReturnStatus                    str
ShipmentProvider                str
WarehouseLocation               str
OrderPriority                   str
dtype: object

In [72]:
# Manage String
df.sample(10)
df['PaymentMethod'] = df['PaymentMethod'].str.replace('paypall','Paypal')

In [73]:
# Check Null Data
print(df.isnull().sum())
print(df.describe())

InvoiceNo               0
StockCode               0
Description             0
Quantity                0
InvoiceDate             0
UnitPrice               0
CustomerID           4978
Country                 0
Discount                0
PaymentMethod           0
ShippingCost         2489
Category                0
SalesChannel            0
ReturnStatus            0
ShipmentProvider        0
WarehouseLocation    3485
OrderPriority           0
dtype: int64
           InvoiceNo      Quantity          InvoiceDate     UnitPrice  \
count   49782.000000  49782.000000                49782  49782.000000
mean   550681.239946     22.372343  2022-11-03 02:30:00     47.537862
min    100005.000000    -50.000000  2020-01-01 00:00:00    -99.980000
25%    324543.000000     11.000000  2021-06-02 13:15:00     23.592500
50%    552244.000000     23.000000  2022-11-03 02:30:00     48.920000
75%    776364.000000     37.000000  2024-04-04 15:45:00     74.610000
max    999997.000000     49.000000  2025-09-05 05:00:00    100.000000
std    260703.009944     17.917774                  NaN     33.479510

         CustomerID      Discount  ShippingCost
count  44804.000000  49782.000000  47293.000000
mean   55032.871775      0.275748     17.494529
min    10001.000000      0.000000      5.000000
25%    32750.750000      0.130000     11.220000
50%    55165.000000      0.260000     17.500000
75%    77306.250000      0.380000     23.720000
max    99998.000000      1.999764     30.000000
std    25913.660157      0.230077      7.220557

In [74]:
#Fill Null Value

df['CustomerID'] = df['CustomerID'].fillna('Unknown')
df['ShippingCost'] = df['ShippingCost'].fillna(df['ShippingCost'].median()) 
df['WarehouseLocation'] =df['WarehouseLocation'].fillna('Unknown')

print(df.isnull().sum())

InvoiceNo            0
StockCode            0
Description          0
Quantity             0
InvoiceDate          0
UnitPrice            0
CustomerID           0
Country              0
Discount             0
PaymentMethod        0
ShippingCost         0
Category             0
SalesChannel         0
ReturnStatus         0
ShipmentProvider     0
WarehouseLocation    0
OrderPriority        0
dtype: int64

In [75]:
# Chaneg Negative Value
df['Quantity'] = df['Quantity'].abs()
df['UnitPrice'] = df['UnitPrice'].abs()
df.describe()

,InvoiceNo,Quantity,InvoiceDate,UnitPrice,Discount,ShippingCost
count,49782.000000,49782.000000,49782,49782.000000,49782.000000,49782.000000
mean,550681.239946,24.925555,2022-11-03 02:30:00,50.625031,0.275748,17.494803
min,100005.000000,1.000000,2020-01-01 00:00:00,1.000000,0.000000,5.000000
25%,324543.000000,13.000000,2021-06-02 13:15:00,25.862500,0.130000,11.540000
50%,552244.000000,25.000000,2022-11-03 02:30:00,50.555000,0.260000,17.500000
75%,776364.000000,37.000000,2024-04-04 15:45:00,75.370000,0.380000,23.410000
max,999997.000000,50.000000,2025-09-05 05:00:00,100.000000,1.999764,30.000000
std,260703.009944,14.152125,NaN,28.597658,0.230077,7.037732

In [76]:
# Inspecdata Before Export
df.info()
df.sample(5)

<class 'pandas.DataFrame'>
RangeIndex: 49782 entries, 0 to 49781
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   InvoiceNo          49782 non-null  int64
 1   StockCode          49782 non-null  str
 2   Description        49782 non-null  str
 3   Quantity           49782 non-null  int64
 4   InvoiceDate        49782 non-null  datetime64[us]
 5   UnitPrice          49782 non-null  float64
 6   CustomerID         49782 non-null  object
 7   Country            49782 non-null  str
 8   Discount           49782 non-null  float64
 9   PaymentMethod      49782 non-null  str
 10  ShippingCost       49782 non-null  float64
 11  Category           49782 non-null  str
 12  SalesChannel       49782 non-null  str
 13  ReturnStatus       49782 non-null  str
 14  ShipmentProvider   49782 non-null  str
 15  WarehouseLocation  49782 non-null  str
 16  OrderPriority      49782 non-null  str
dtypes: datetime64[us](1), float64(3), int64(2), object(1), str(10)
memory usage: 6.5+ MB

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
34305,966275,SKU_1089,Desk Lamp,36,2023-11-30 09:00:00,11.72,13585.0,Portugal,0.13,Credit Card,22.07,Stationery,In-store,Not Returned,UPS,London,Medium
41445,343762,SKU_1522,T-shirt,31,2024-09-22 21:00:00,57.64,73660.0,Italy,0.08,Bank Transfer,26.61,Electronics,In-store,Not Returned,UPS,London,Low
34904,753398,SKU_1544,Wall Clock,19,2023-12-25 08:00:00,76.62,32305.0,Germany,0.21,Credit Card,25.39,Furniture,Online,Not Returned,FedEx,London,Low
44231,418372,SKU_1665,USB Cable,48,2025-01-16 23:00:00,76.05,56819.0,Germany,0.46,Bank Transfer,27.45,Electronics,Online,Not Returned,UPS,Amsterdam,High
29516,444390,SKU_1972,Office Chair,20,2023-05-14 20:00:00,50.34,28564.0,United Kingdom,0.15,Bank Transfer,6.73,Accessories,In-store,Not Returned,DHL,Amsterdam,High

In [77]:
# Export to CSV
df.to_csv('cleaned_online_sales.csv', index=False)