In [29]:
import pandas as pd

df = pd.read_csv('sub_components2025_2026.csv')

In [30]:
#Check data frame
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 11300 entries, 0 to 11299
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATE                11300 non-null  str
 1   ITEM                11300 non-null  str
 2   NAME                11300 non-null  str
 3   SPEC                11300 non-null  str
 4   DRAWING             9780 non-null   str
 5   AC_CODE             11300 non-null  str
 6   WC_CODE             11260 non-null  str
 7   LOC                 11300 non-null  str
 8   DEPT                11300 non-null  int64
 9   VD_CODE             11300 non-null  str
 10  VD_NAME             11300 non-null  str
 11  UP                  11299 non-null  float64
 12  CUR                 11300 non-null  str
 13  PURLT               11300 non-null  int64
 14  ORDER_BAL           11300 non-null  int64
 15  SAFETY_STOCK        11300 non-null  int64
 16  ITEM_TYPE           11300 non-null  str
 17  UNIT                11300 non-null  str
 18  BEGIN_QTY           11300 non-null  float64
 19  RECEIVE_QTY         11300 non-null  float64
 20  ISSUE_QTY           11300 non-null  float64
 21  STOCK_QTY           11300 non-null  float64
 22  BEGIN_AMOUNT        11300 non-null  float64
 23  RECEIVE_AMOUNT      11300 non-null  float64
 24  ISSUE_AMOUNT        11300 non-null  float64
 25  STOCK_AMOUNT        11300 non-null  float64
 26  LAST_ISSUED_DATE    10180 non-null  str
 27  LAST_STOCK_IN_DATE  11300 non-null  str
dtypes: float64(9), int64(4), str(15)
memory usage: 2.4 MB

,DATE,ITEM,NAME,SPEC,DRAWING,AC_CODE,WC_CODE,LOC,DEPT,VD_CODE,...,BEGIN_QTY,RECEIVE_QTY,ISSUE_QTY,STOCK_QTY,BEGIN_AMOUNT,RECEIVE_AMOUNT,ISSUE_AMOUNT,STOCK_AMOUNT,LAST_ISSUED_DATE,LAST_STOCK_IN_DATE
0,1/1/2025,SKU-0001,STEEL BAR,STE-001,BP-2012D S,4520AA,TN29,3,90,NIP262,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,8/6/2026,28/8/2026
1,1/1/2025,SKU-0002,STEEL BAR,STE-004,BP-2012D S,4520AA,TN29,3,90,NIP262,...,1726.0,16977.0,14193.0,4510.0,102651.26,992645.19,831179.12,264117.33,3/7/2025,18/7/2025
2,1/1/2025,SKU-0003,STEEL BAR,STE-003,BP-2012D S,4520AA,TN29,3,90,NIP262,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,5/8/2026,31/8/2026
3,1/1/2025,SKU-0004,STEEL BAR,STE-004,BP-2012D S,4520AA,TN29,3,90,NIP262,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,6/6/2026,22/5/2026
4,1/1/2025,SKU-0005,STEEL BAR,STE-005,BP-2012O,4520AA,TN29,3,90,NIP262,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,11/5/2025,25/4/2025

In [31]:
# Drop unnecessary columns
df = df.drop(columns=['DEPT','DRAWING','PURLT','SAFETY_STOCK','ITEM_TYPE'])
df.head()

,DATE,ITEM,NAME,SPEC,AC_CODE,WC_CODE,LOC,VD_CODE,VD_NAME,UP,...,BEGIN_QTY,RECEIVE_QTY,ISSUE_QTY,STOCK_QTY,BEGIN_AMOUNT,RECEIVE_AMOUNT,ISSUE_AMOUNT,STOCK_AMOUNT,LAST_ISSUED_DATE,LAST_STOCK_IN_DATE
0,1/1/2025,SKU-0001,STEEL BAR,STE-001,4520AA,TN29,3,NIP262,Nippon Precision Bar,NaN,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,8/6/2026,28/8/2026
1,1/1/2025,SKU-0002,STEEL BAR,STE-004,4520AA,TN29,3,NIP262,Nippon Precision Bar,88.150766,...,1726.0,16977.0,14193.0,4510.0,102651.26,992645.19,831179.12,264117.33,3/7/2025,18/7/2025
2,1/1/2025,SKU-0003,STEEL BAR,STE-003,4520AA,TN29,3,NIP262,Nippon Precision Bar,0.000000,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,5/8/2026,31/8/2026
3,1/1/2025,SKU-0004,STEEL BAR,STE-004,4520AA,TN29,3,NIP262,Nippon Precision Bar,0.000000,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,6/6/2026,22/5/2026
4,1/1/2025,SKU-0005,STEEL BAR,STE-005,4520AA,TN29,3,NIP262,Nippon Precision Bar,0.000000,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,11/5/2025,25/4/2025

In [ ]:
# Change Data Type
date_cols = ['DATE', 'LAST_ISSUED_DATE', 'LAST_STOCK_IN_DATE']

for col in date_cols:
    df[col] = pd.to_datetime(df[col], format='%d/%m/%Y', errors='coerce')

qty_amount_cols = ['BEGIN_QTY','RECEIVE_QTY','ISSUE_QTY','STOCK_QTY',
                    'BEGIN_AMOUNT','RECEIVE_AMOUNT','STOCK_AMOUNT','ISSUE_AMOUNT']

df[qty_amount_cols] = df[qty_amount_cols].astype('int64')
df.dtypes

DATE                  datetime64[us]
ITEM                             str
NAME                             str
SPEC                             str
AC_CODE                          str
WC_CODE                          str
LOC                              str
VD_CODE                          str
VD_NAME                          str
UP                           float64
CUR                              str
ORDER_BAL                      int64
UNIT                             str
BEGIN_QTY                      int64
RECEIVE_QTY                    int64
ISSUE_QTY                      int64
STOCK_QTY                      int64
BEGIN_AMOUNT                   int64
RECEIVE_AMOUNT                 int64
ISSUE_AMOUNT                   int64
STOCK_AMOUNT                   int64
LAST_ISSUED_DATE      datetime64[us]
LAST_STOCK_IN_DATE    datetime64[us]
dtype: object

In [ ]:
#Check Null Values
df.isnull().sum()

DATE                     0
ITEM                     0
NAME                     0
SPEC                     0
AC_CODE                  0
WC_CODE                 40
LOC                      0
VD_CODE                  0
VD_NAME                  0
UP                       1
CUR                      0
ORDER_BAL                0
UNIT                     0
BEGIN_QTY                0
RECEIVE_QTY              0
ISSUE_QTY                0
STOCK_QTY                0
BEGIN_AMOUNT             0
RECEIVE_AMOUNT           0
ISSUE_AMOUNT             0
STOCK_AMOUNT             0
LAST_ISSUED_DATE      1120
LAST_STOCK_IN_DATE       0
dtype: int64