In [16]:
import pandas as pd

df = pd.read_csv('crime_incidents.csv')

print('\n จำนวนแถวและคอลัมน์ของ DataFrame:')
print(df.shape)
print('\n ชนิดข้อมูลและจำนวนค่าที่ไม่ใช่ค่า null ของแต่ละคอลัมน์:')
print(df.info())
print('\n ข้อมูลที่ซ้ำกัน:')
print(df.duplicated().sum())
print('\n ตัวอย่างข้อมูล 5 แถวแรกของ DataFrame:')
display(df.sample(5))

 จำนวนแถวและคอลัมน์ของ DataFrame:
(5250, 33)

 ชนิดข้อมูลและจำนวนค่าที่ไม่ใช่ค่า null ของแต่ละคอลัมน์:
<class 'pandas.DataFrame'>
RangeIndex: 5250 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5250 non-null   str
 1   crime_type          5250 non-null   str
 2   district            5250 non-null   str
 3   city                5250 non-null   str
 4   state               5250 non-null   str
 5   address             5250 non-null   str
 6   latitude            4992 non-null   float64
 7   longitude           4961 non-null   float64
 8   incident_datetime   4910 non-null   str
 9   officer_id          5250 non-null   str
 10  officer_first_name  5250 non-null   str
 11  officer_last_name   5250 non-null   str
 12  badge_number        4938 non-null   float64
 13  suspect_id          4440 non-null   str
 14  suspect_first_name  4440 non-null   str
 15  suspect_last_name   4440 non-null   str
 16  suspect_age         4153 non-null   float64
 17  suspect_gender      3837 non-null   str
 18  suspect_race        3649 non-null   str
 19  victim_id           4993 non-null   str
 20  victim_first_name   4993 non-null   str
 21  victim_last_name    4993 non-null   str
 22  victim_age          4688 non-null   float64
 23  victim_gender       4250 non-null   str
 24  victim_phone        4194 non-null   str
 25  weapon_used         4280 non-null   str
 26  severity            4895 non-null   str
 27  case_status         4519 non-null   str
 28  resolution          4299 non-null   str
 29  num_arrests         4917 non-null   float64
 30  property_loss_usd   4814 non-null   str
 31  reported_online     4746 non-null   str
 32  notes               4181 non-null   str
dtypes: float64(6), str(27)
memory usage: 1.3 MB
None

 ข้อมูลที่ซ้ำกัน:
200

 ตัวอย่างข้อมูล 5 แถวแรกของ DataFrame:

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,...,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
2252,INC003743,Assault,Cen,Maplewood,PA,5061 River Rd,46.268418,-100.566603,27/11/2022 0:40,OFF0028,...,MALE,826-551-9189,Blunt Object,Med,Closed,No Arrest,2.0,30374.07,1,NaN
1056,INC001753,ROBBERY,Mid,Centerville,AZ,8940 Lincoln St,41.900076,-116.317475,05/31/2024 22:36,OFF0100,...,Unknown,611-560-3710,blunt object,Critical,OPEN,NO ARREST,5.0,3641.15,0,Incident at 8940 Lincoln St. Officer responded...
3647,INC004767,Kidnaping,East,Springfield,TX,802 Elm Blvd,182.626000,NaN,22/1/2021 7:17,OFF0141,...,Unknown,204-921-5504,Bat,MEDIUM,CLOSED,Arres Made,2.0,45566.58.0,1,Incident at 802 Elm Blvd. Officer responded at...
2280,INC001366,fraud,Central,Fairview,FL,1077 Elm Blvd,45.045316,-103.656977,23/4/2019 3:40,OFF0065,...,NaN,NaN,NaN,4,closed,NaN,NaN,45865.31,NaN,Incident at 1077 Elm Blvd. Officer responded a...
1765,INC002332,Kidnaping,northwest,Riverside,CA,4932 Oak Ave,38.225752,-78.981051,NaN,OFF0072,...,Female,628-666-8419,Knife,High,under investigation,No Arrest,0.0,19591.63,0,Incident at 4932 Oak Ave. Officer responded at...

In [17]:
#ลบแถวซ้ำ
df.duplicated().sum()
print(df.shape)

df = df.drop_duplicates()
print('\n จำนวนแถวและคอลัมน์ของ DataFrame หลังจากลบแถวซ้ำ:')
print(df.shape)

(5250, 33)

 จำนวนแถวและคอลัมน์ของ DataFrame หลังจากลบแถวซ้ำ:
(5050, 33)

In [18]:
#เปลี่ยนชนิดข้อมูล


df['incident_datetime'] = pd.to_datetime(df['incident_datetime'],errors='coerce')
df['property_loss_usd'] = pd.to_numeric(df['property_loss_usd'], errors='coerce')

df.info()

<class 'pandas.DataFrame'>
Index: 5050 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5050 non-null   str
 1   crime_type          5050 non-null   str
 2   district            5050 non-null   str
 3   city                5050 non-null   str
 4   state               5050 non-null   str
 5   address             5050 non-null   str
 6   latitude            4799 non-null   float64
 7   longitude           4772 non-null   float64
 8   incident_datetime   4457 non-null   datetime64[us]
 9   officer_id          5050 non-null   str
 10  officer_first_name  5050 non-null   str
 11  officer_last_name   5050 non-null   str
 12  badge_number        4749 non-null   float64
 13  suspect_id          4275 non-null   str
 14  suspect_first_name  4275 non-null   str
 15  suspect_last_name   4275 non-null   str
 16  suspect_age         3998 non-null   float64
 17  suspect_gender      3698 non-null   str
 18  suspect_race        3525 non-null   str
 19  victim_id           4802 non-null   str
 20  victim_first_name   4802 non-null   str
 21  victim_last_name    4802 non-null   str
 22  victim_age          4508 non-null   float64
 23  victim_gender       4087 non-null   str
 24  victim_phone        4031 non-null   str
 25  weapon_used         4120 non-null   str
 26  severity            4708 non-null   str
 27  case_status         4354 non-null   str
 28  resolution          4138 non-null   str
 29  num_arrests         4726 non-null   float64
 30  property_loss_usd   4500 non-null   float64
 31  reported_online     4564 non-null   str
 32  notes               4022 non-null   str
dtypes: datetime64[us](1), float64(7), str(25)
memory usage: 1.3 MB

C:\Users\boat\AppData\Local\Temp\ipykernel_22388\327671561.py:4: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['incident_datetime'] = pd.to_datetime(df['incident_datetime'],errors='coerce')

In [22]:
# เติมข้อมูลหาย


num_cols = df.select_dtypes(include=['number']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

str_cols = df.select_dtypes(include=['object']).columns
df[str_cols] = df[str_cols].fillna('Unknown')
print(df.isna().sum())

df['incident_datetime'] = df['incident_datetime'].ffill()

incident_id           0
crime_type            0
district              0
city                  0
state                 0
address               0
latitude              0
longitude             0
incident_datetime     0
officer_id            0
officer_first_name    0
officer_last_name     0
badge_number          0
suspect_id            0
suspect_first_name    0
suspect_last_name     0
suspect_age           0
suspect_gender        0
suspect_race          0
victim_id             0
victim_first_name     0
victim_last_name      0
victim_age            0
victim_gender         0
victim_phone          0
weapon_used           0
severity              0
case_status           0
resolution            0
num_arrests           0
property_loss_usd     0
reported_online       0
notes                 0
dtype: int64

C:\Users\boat\AppData\Local\Temp\ipykernel_22388\534587249.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_cols = df.select_dtypes(include=['object']).columns

In [25]:

display(df.select_dtypes(include=['string', 'object']).sample(10))

,incident_id,crime_type,district,city,state,address,officer_id,officer_first_name,officer_last_name,suspect_id,...,victim_first_name,victim_last_name,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,reported_online,notes
4553,INC001940,Roberry,Cen,Fairview,OH,9898 Elm Blvd,OFF0027,Matthew,Taylor,SUS00484,...,Michael,Thomas,M,3477851021,blunt object,MEDIUM,Pendng,Unknown,TRUE,Unknown
287,INC002677,HOMOCIDE,NORTHEAST,Centerville,NY,815 Sunset Blvd,OFF0075,Jennifer,Garcia,SUS00460,...,John,Miller,Unknown,906-384-3227,Rifle,Medium,Pendng,arrest made,Yes,Incident at 815 Sunset Blvd. Officer responded...
4706,INC004529,Arsen,north,Oakdale,GA,8842 Cedar Lane,OFF0042,Chris,Johnson,SUS00731,...,Richard,Nguyen,m,239-744-9472,hands,4,CLOSED,Dismissed,1,Incident at 8842 Cedar Lane. Officer responded...
2481,INC000802,Dom. Violence,WEST,Springfield,TX,1378 Cedar Lane,OFF0078,Joseph,Taylor,SUS00745,...,Charles,Lee,Unknown,627-569-9749,Blunt Object,Crit,OPEN,arrest made,NO,Incident at 1378 Cedar Lane. Officer responded...
255,INC000815,Armed Robbery,northwest,Riverside,FL,7701 Maple Dr,OFF0053,Nancy,Wright,SUS00348,...,Jennifer,Flores,FEMALE,218-190-8444,Unarmed,Medium,Unknown,Arrest Made,YES,Incident at 7701 Maple Dr. Officer responded a...
2691,INC002085,Deception,South,Riverside,NC,5808 Maple Dr,OFF0114,Richard,Allen,SUS00104,...,Nancy,Walker,male,941-161-3346,Gun,3,closed,Arrest Made,1,Incident at 5808 Maple Dr. Officer responded a...
2866,INC000283,Cybercrime,Northeast,Springfield,TX,1071 Oak Ave,OFF0085,Michelle,Williams,SUS00366,...,David,Young,MALE,Unknown,Gun,low,Closed,Dismissed,yes,Unknown
1978,INC002050,DWI,Sou,Springfield,CA,5650 Washington Ave,OFF0150,Chris,Lee,SUS00365,...,Richard,Martin,Male,692-417-3001,blunt object,Med,Pendng,warning,no,Unknown
921,INC000725,Tresspassing,Midtown,Centerville,GA,7438 Sunset Blvd,OFF0017,Michael,Martin,SUS00476,...,Charles,Davis,MALE,858-751-3633,Knife,low,under investigation,warning,NO,Unknown
823,INC003704,Drug Offence,Nor,Oakdale,FL,6630 Main St,OFF0011,Karen,Thomas,Unknown,...,Mary,Scott,Female,780-341-5241,Unknown,high,Open,NO ARREST,FALSE,Unknown