In [71]:
#Import Pandas Library
import pandas as pd

#Import CSV file
df = pd.read_csv('crime_incidents.csv')

print('\n จำนวนแถวและคอลัมน์ของ DataFrame:')
print(df.shape)
print('\n ชนิดข้อมูลและจำนวนค่าที่ไม่ใช่ค่า null ของแต่ละคอลัมน์:')
print(df.info())
print('\n ข้อมูลที่ซ้ำกัน:')
print(df.duplicated().sum())
print('\n ตัวอย่างข้อมูล 5 แถวแรกของ DataFrame:')
display(df.sample(5))

 จำนวนแถวและคอลัมน์ของ DataFrame:
(5250, 33)

 ชนิดข้อมูลและจำนวนค่าที่ไม่ใช่ค่า null ของแต่ละคอลัมน์:
<class 'pandas.DataFrame'>
RangeIndex: 5250 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5250 non-null   str
 1   crime_type          5250 non-null   str
 2   district            5250 non-null   str
 3   city                5250 non-null   str
 4   state               5250 non-null   str
 5   address             5250 non-null   str
 6   latitude            4992 non-null   float64
 7   longitude           4961 non-null   float64
 8   incident_datetime   4910 non-null   str
 9   officer_id          5250 non-null   str
 10  officer_first_name  5250 non-null   str
 11  officer_last_name   5250 non-null   str
 12  badge_number        4938 non-null   float64
 13  suspect_id          4440 non-null   str
 14  suspect_first_name  4440 non-null   str
 15  suspect_last_name   4440 non-null   str
 16  suspect_age         4153 non-null   float64
 17  suspect_gender      3837 non-null   str
 18  suspect_race        3649 non-null   str
 19  victim_id           4993 non-null   str
 20  victim_first_name   4993 non-null   str
 21  victim_last_name    4993 non-null   str
 22  victim_age          4688 non-null   float64
 23  victim_gender       4250 non-null   str
 24  victim_phone        4194 non-null   str
 25  weapon_used         4280 non-null   str
 26  severity            4895 non-null   str
 27  case_status         4519 non-null   str
 28  resolution          4299 non-null   str
 29  num_arrests         4917 non-null   float64
 30  property_loss_usd   4814 non-null   str
 31  reported_online     4746 non-null   str
 32  notes               4181 non-null   str
dtypes: float64(6), str(27)
memory usage: 1.3 MB
None

 ข้อมูลที่ซ้ำกัน:
200

 ตัวอย่างข้อมูล 5 แถวแรกของ DataFrame:

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,officer_first_name,officer_last_name,badge_number,suspect_id,suspect_first_name,suspect_last_name,suspect_age,suspect_gender,suspect_race,victim_id,victim_first_name,victim_last_name,victim_age,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
5052,INC004558,Domestc Violence,SOUTH,Centerville,PA,6350 Maple Dr,35.321829,-94.950085,23/6/2020 8:20,OFF0075,Nancy,Harris,8142.0,SUS00636,Barbara,Anderson,45.0,Unknown,white,VIC00034,John,White,25.0,Male,668-997-6624,NaN,low,Pendng,warning,4.0,NaN,FALSE,Incident at 6350 Maple Dr. Officer responded a...
3126,INC000800,Homicide,SOUTHEAST,Springfield,CA,3284 Cedar Lane,33.200530,-94.550588,16/4/2022 6:16,OFF0071,Carol,Martin,7490.0,SUS00338,Sarah,Scott,28.0,MALE,Other,VIC00800,Richard,Thomas,58.0,Male,653-238-4590,Bat,high,NaN,Arrest Made,2.0,42560.07,0,Incident at 3284 Cedar Lane. Officer responded...
778,INC003905,DRUG OFFENSE,East,Lakewood,NC,8329 Elm Blvd,36.525133,-73.795807,12/7/2021 9:36,OFF0101,Donna,Green,8551.0,SUS00009,Mark,Wilson,54.0,NaN,NaN,VIC00728,Emily,Lee,26.0,Other,644-298-3981,NaN,MEDIUM,Closed,Dismissed,1.0,23363.44,1,NaN
639,INC004324,ROBBERY,Eas,Hillcrest,CA,1775 Park Rd,28.376544,-85.915110,12/4/2023,OFF0139,Chris,Young,1679.0,SUS00709,Karen,Anderson,53.0,Male,NaN,VIC00424,Michael,Hill,55.0,M,2848279293,Pistol,4,under investigation,arrest made,5.0,48435.3,0,Incident at 1775 Park Rd. Officer responded at...
1491,INC003143,robbery,North,Fairview,FL,6111 Main St,36.503196,-75.076618,14/7/2021 6:32,OFF0035,David,Allen,8504.0,SUS00219,William,Taylor,59.0,FEMALE,Hispanic,VIC00828,Michelle,Brown,77.0,MALE,728-497-6383,NaN,Med,Pending,NaN,2.0,47536.97,FALSE,Incident at 6111 Main St. Officer responded at...

In [72]:
#Check duplicated rows
print(df.duplicated().sum())
print(df.shape)

#Delete duplicated rows
df = df.drop_duplicates()
print(df.shape)

200
(5250, 33)
(5050, 33)

In [73]:
#Change data types
df['incident_datetime'] = pd.to_datetime(df['incident_datetime'],errors='coerce')
df['property_loss_usd'] = pd.to_numeric(df['property_loss_usd'], errors='coerce')
df['victim_age'] = pd.to_numeric(df['victim_age'], errors='coerce')

df.info()

<class 'pandas.DataFrame'>
Index: 5050 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5050 non-null   str
 1   crime_type          5050 non-null   str
 2   district            5050 non-null   str
 3   city                5050 non-null   str
 4   state               5050 non-null   str
 5   address             5050 non-null   str
 6   latitude            4799 non-null   float64
 7   longitude           4772 non-null   float64
 8   incident_datetime   4457 non-null   datetime64[us]
 9   officer_id          5050 non-null   str
 10  officer_first_name  5050 non-null   str
 11  officer_last_name   5050 non-null   str
 12  badge_number        4749 non-null   float64
 13  suspect_id          4275 non-null   str
 14  suspect_first_name  4275 non-null   str
 15  suspect_last_name   4275 non-null   str
 16  suspect_age         3998 non-null   float64
 17  suspect_gender      3698 non-null   str
 18  suspect_race        3525 non-null   str
 19  victim_id           4802 non-null   str
 20  victim_first_name   4802 non-null   str
 21  victim_last_name    4802 non-null   str
 22  victim_age          4508 non-null   float64
 23  victim_gender       4087 non-null   str
 24  victim_phone        4031 non-null   str
 25  weapon_used         4120 non-null   str
 26  severity            4708 non-null   str
 27  case_status         4354 non-null   str
 28  resolution          4138 non-null   str
 29  num_arrests         4726 non-null   float64
 30  property_loss_usd   4500 non-null   float64
 31  reported_online     4564 non-null   str
 32  notes               4022 non-null   str
dtypes: datetime64[us](1), float64(7), str(25)
memory usage: 1.3 MB

C:\Users\bpt7474\AppData\Local\Temp\ipykernel_3852\379047736.py:2: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['incident_datetime'] = pd.to_datetime(df['incident_datetime'],errors='coerce')

In [74]:
# Check and Fill missing values

df = df.fillna({
    'latitude': df['latitude'].mean(),
    'longitude': df['longitude'].mean(),
    'incident_datetime' : df['incident_datetime'].ffill(),
    'badge_number' : df['badge_number'].mean(),
    'suspect_id' : 'unknown',
    'suspect_first_name' : 'unknown',
    'suspect_last_name' : 'unknown',
    'suspect_age' : df['suspect_age'].mean(),
    'suspect_gender' : 'unknown',
    'suspect_race' : 'unknown',
    'victim_id' : 'unknown',
    'victim_first_name' : 'unknown',
    'victim_last_name' : 'unknown',
    'victim_age' : df['victim_age'].mean(),
    'victim_gender' : 'unknown',
    'victim_phone' : 'unknown',
    'weapon_used' : 'unknown',
    'severity' : 'unknown',
    'case_status' : 'unknown',
    'resolution' : 'unknown',
    'num_arrests' : 0,
    'property_loss_usd' : df['property_loss_usd'].mean(),
    'reported_online' : 'unknown',
    'notes' : 'unknown'
})

print('\n-------------ข้อมูลหลังการเติมข้อมูล-------------')
print(df.isna().sum())

-------------ข้อมูลหลังการเติมข้อมูล-------------
incident_id           0
crime_type            0
district              0
city                  0
state                 0
address               0
latitude              0
longitude             0
incident_datetime     0
officer_id            0
officer_first_name    0
officer_last_name     0
badge_number          0
suspect_id            0
suspect_first_name    0
suspect_last_name     0
suspect_age           0
suspect_gender        0
suspect_race          0
victim_id             0
victim_first_name     0
victim_last_name      0
victim_age            0
victim_gender         0
victim_phone          0
weapon_used           0
severity              0
case_status           0
resolution            0
num_arrests           0
property_loss_usd     0
reported_online       0
notes                 0
dtype: int64

In [75]:
# Change to lower string
pd.set_option('display.max_columns', 35)


column_str = ['crime_type', 'district', 'city', 'suspect_gender', 'suspect_race', 'victim_gender', 'severity', 'resolution','reported_online','case_status','weapon_used']

# ใช้ .apply เพื่อสั่งให้ทุกคอลัมน์ในรายชื่อแปลงเป็นตัวพิมพ์เล็ก
df[column_str] = df[column_str].apply(lambda x: x.str.lower())

In [76]:
df.sample(10)

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,officer_first_name,officer_last_name,badge_number,suspect_id,suspect_first_name,suspect_last_name,suspect_age,suspect_gender,suspect_race,victim_id,victim_first_name,victim_last_name,victim_age,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
4199,INC000894,property damage,northwest,hillcrest,AZ,7467 Main St,36.214640,-102.764070,2022-01-12 10:54:00,OFF0114,James,Lee,7078.0,SUS00661,Chris,Thomas,74.00000,other,black,VIC00685,Joseph,Thomas,32.000000,female,930-772-4312,unknown,high,closed,warning,1.0,165.83,0,Incident at 7467 Main St. Officer responded at...
556,INC004009,drunk driving,southwest,riverside,AZ,5939 Oak Ave,40.740995,-118.929897,2018-11-29 05:20:00,OFF0005,Sarah,Scott,8137.0,SUS00681,William,Allen,30.00000,f,unknown,VIC00648,Michael,Davis,20.000000,f,unknown,knife,critical,under investigation,warning issued,1.0,410.47,no,unknown
4688,INC004664,burglary,west,maplewood,GA,419 River Rd,34.635175,-108.665529,2024-05-18 10:37:00,OFF0053,William,Wilson,4027.0,SUS00652,Thomas,Jones,44.00000,m,other,VIC00134,Patricia,Lee,53.000000,female,unknown,unknown,critical,pending,arrest made,1.0,12922.55,no,Incident at 419 River Rd. Officer responded at...
1611,INC004627,b&e,central,springfield,AZ,3951 Sunset Blvd,40.714396,-96.367008,2021-10-28 17:55:00,OFF0137,Joseph,Jackson,6502.0,SUS00585,James,Hill,39.00000,female,asian,VIC00885,Anthony,Taylor,33.000000,male,987-138-7707,hands/feet,high,pending,no arrest,4.0,33954.02,no,Incident at 3951 Sunset Blvd. Officer responde...
4775,INC004236,sexual assault,south,riverside,GA,2770 Sunset Blvd,45.425665,-95.709747,2024-03-12 07:06:00,OFF0107,James,Green,4508.0,SUS00516,Mark,Young,24.00000,m,hispanic,VIC00582,Emily,Moore,79.000000,m,870-357-6843,pistol,high,pendng,arres made,0.0,16581.17,no,Incident at 2770 Sunset Blvd. Officer responde...
1274,INC002019,homicide,nor,lakewood,GA,4175 Maple Dr,30.383609,-117.179041,2021-01-12 08:12:00,OFF0136,Joseph,Johnson,8460.0,unknown,unknown,unknown,48.56003,unknown,unknown,VIC00689,Daniel,Brown,34.000000,unknown,730-953-3674,blunt object,unknown,open,dismissed,3.0,2049.51,yes,Incident at 4175 Maple Dr. Officer responded a...
117,INC004408,robbery,north,hillcrest,GA,305 Main St,43.402906,-93.503354,2024-01-26 14:12:00,OFF0148,Barbara,Anderson,8387.0,SUS00417,Charles,Wilson,22.00000,female,hispanic,VIC00909,Jennifer,Green,61.000000,f,951-854-2345,hands/feet,medium,investgation,warning issued,0.0,17530.72,no,Incident at 305 Main St. Officer responded at ...
1935,INC002674,drunk driving,southeast,centerville,GA,1239 River Rd,33.413210,-88.751699,2021-09-29 05:48:00,OFF0059,Chris,Williams,3028.0,SUS00312,Jessica,Moore,47.00000,male,hispanic,VIC00584,Jessica,White,40.000000,unknown,unknown,hands/feet,unknown,under investigation,dismissed,2.0,26608.87,no,unknown
395,INC001273,arson,central,hillcrest,TX,7546 Cedar Lane,30.756101,-87.023520,2020-11-07 04:28:00,OFF0032,Donna,Young,6875.0,SUS00259,Jennifer,Hall,29.00000,male,other,unknown,unknown,unknown,52.228039,unknown,unknown,rifle,1,under investigation,unknown,4.0,47695.20,no,Incident at 7546 Cedar Lane. Officer responded...
1879,INC004834,burglary,southeast,oakdale,GA,527 Oak Ave,42.208930,-78.600784,2021-10-08 21:25:00,OFF0060,Barbara,Hall,6503.0,SUS00397,Charles,Torres,16.00000,m,white,VIC00443,Thomas,Nguyen,76.000000,unknown,877-939-7303,blunt object,high,closed,case dismissed,0.0,13500.21,unknown,Incident at 527 Oak Ave. Officer responded at ...

In [77]:
#Change word
# ใช้ .replace() ตรงๆ โดยไม่ต้องใส่ .str และเพิ่ม regex=False เพื่อความแม่นยำ
df['district'] = df['district'].str.strip()
df['district'] = df['district'].replace({'nor':'north','sou':'south', 'cen' : 'central','eas':'east', 'mid' : 'midtown', 'wes' : 'west'})
df['suspect_gender'] = df['suspect_gender'].replace({'m':'male', 'f':'female'}, regex=False)
df['severity'] = df['severity'].replace({'med':'medium','crit':'critical','1':'low', '2':'medium','3':'high', '4':'critical'}, regex=False)
df['case_status'] = df['case_status'].replace({'pendng':'pending','under investigation' : 'investigation','investgation':'investigation'}, regex=False)
df['reported_online'] = df['reported_online'].replace({'true':'yes','false':'no', '1':'yes', '0':'no'}, regex=False)
df['resolution'] = df['resolution'].replace({'case dismissed' : 'dismissed', 'arres made' : 'arrested','arrest made':'arrested', 'warning' : 'warning issued'}, regex=False)
df['victim_gender'] = df['victim_gender'].replace({'m':'male', 'f':'female'}, regex=False)

In [78]:
df.sample(10)

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,officer_first_name,officer_last_name,badge_number,suspect_id,suspect_first_name,suspect_last_name,suspect_age,suspect_gender,suspect_race,victim_id,victim_first_name,victim_last_name,victim_age,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
4113,INC004807,dv,southwest,oakdale,NC,6386 Cedar Lane,41.085433,-110.914219,2023-10-06 12:44:00,OFF0143,Charles,Thomas,5554.343441,SUS00241,Daniel,Johnson,48.56003,male,asian,VIC00817,Nancy,Johnson,27.0,female,755-232-9066,hands/feet,medium,investigation,no arrest,4.0,22188.780000,no,Incident at 6386 Cedar Lane. Officer responded...
692,INC001876,vandalism,east,springfield,CA,1467 Main St,40.740995,-114.782799,2018-05-25 10:29:00,OFF0115,Ashley,Walker,5554.343441,SUS00609,Nancy,Hall,63.00000,female,unknown,VIC00747,Joseph,Wilson,58.0,male,365-281-7646,bat,low,open,warning issued,3.0,12119.020000,yes,Incident at 1467 Main St. Officer responded at...
232,INC000676,tresspassing,midtown,oakdale,TX,7416 Elm Blvd,27.484011,-72.298923,2023-06-11 01:28:00,OFF0087,Matthew,Jones,1135.000000,SUS00641,Emily,Flores,29.00000,male,asian,VIC00786,Emily,Brown,75.0,female,580-523-1272,pistol,critical,pending,arrested,1.0,14407.750000,yes,Incident at 7416 Elm Blvd. Officer responded a...
1096,INC004000,homicide,northwest,oakdale,GA,1559 Oak Ave,26.581233,-91.689874,2022-12-26 19:55:00,OFF0139,Karen,Moore,2756.000000,SUS00621,Mark,Wilson,53.00000,female,hispanic,VIC00774,Anthony,Jackson,11.0,female,(462) -85-7-9893,pistol,critical,resolved,arrested,3.0,22774.688522,yes,Incident at 1559 Oak Ave. Officer responded at...
1816,INC000742,kidnaping,north,hillcrest,CA,3313 Cedar Lane,26.683020,-74.668807,2020-02-03 22:52:00,OFF0104,David,Walker,4097.000000,SUS00129,David,Jackson,61.00000,female,other,VIC00632,Nancy,Hill,66.0,female,937-921-8228,firearm,low,closed,arrested,3.0,22774.688522,no,Incident at 3313 Cedar Lane. Officer responded...
891,INC002067,trespassing,west,lakewood,CA,7908 Oak Ave,25.900732,-82.095167,2019-04-05 07:10:00,OFF0091,Richard,Anderson,3532.000000,SUS00557,Thomas,Hill,48.00000,unknown,black,VIC00865,Nancy,Johnson,65.0,unknown,264-692-3128,unknown,medium,investigation,no arrest,2.0,8238.650000,yes,Incident at 7908 Oak Ave. Officer responded at...
2384,INC004253,theft,south,maplewood,FL,3892 Elm Blvd,32.903826,-96.142171,2018-11-22 02:27:00,OFF0139,John,Nguyen,4272.000000,SUS00649,Patricia,Johnson,16.00000,male,hispanic,VIC00872,Mary,Thompson,26.0,male,377-628-8134,firearm,critical,pending,unknown,1.0,48003.330000,no,Incident at 3892 Elm Blvd. Officer responded a...
3750,INC004392,cyber crime,southeast,fairview,OH,3442 Oak Ave,42.662493,-70.458187,2023-01-25 22:30:00,OFF0043,Joseph,Scott,7819.000000,SUS00060,David,Hill,58.00000,male,black,VIC00011,Charles,Young,80.0,unknown,282-414-1256,gun,medium,open,warning issued,4.0,39041.030000,yes,Incident at 3442 Oak Ave. Officer responded at...
1978,INC002050,dwi,south,springfield,CA,5650 Washington Ave,142.399600,-87.089039,2024-04-08 22:12:00,OFF0150,Chris,Lee,6035.000000,SUS00365,Patricia,Brown,16.00000,other,unknown,VIC00006,Richard,Martin,45.0,male,692-417-3001,blunt object,medium,pending,warning issued,3.0,49854.610000,no,unknown
143,INC004335,assault,northeast,oakdale,FL,263 Maple Dr,44.446359,-114.541218,2019-08-30 08:53:00,OFF0055,donna,Thompson,5554.343441,SUS00630,Joseph,Brown,40.00000,male,black,VIC00387,Patricia,Young,60.0,male,564-536-4844,hands,high,unknown,warning issued,2.0,-19857.760000,no,Incident at 263 Maple Dr. Officer responded at...

In [79]:
# Change negative values to positive
df['victim_age'] = df['victim_age'].abs()
df['suspect_age'] = df['suspect_age'].abs()
df['property_loss_usd'] = df['property_loss_usd'].abs()
df['num_arrests'] = df['num_arrests'].abs()

print((df['victim_age']<0).sum())
print((df['suspect_age']<0).sum())
print(df.info())

0
0
<class 'pandas.DataFrame'>
Index: 5050 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5050 non-null   str
 1   crime_type          5050 non-null   str
 2   district            5050 non-null   str
 3   city                5050 non-null   str
 4   state               5050 non-null   str
 5   address             5050 non-null   str
 6   latitude            5050 non-null   float64
 7   longitude           5050 non-null   float64
 8   incident_datetime   5050 non-null   datetime64[us]
 9   officer_id          5050 non-null   str
 10  officer_first_name  5050 non-null   str
 11  officer_last_name   5050 non-null   str
 12  badge_number        5050 non-null   float64
 13  suspect_id          5050 non-null   str
 14  suspect_first_name  5050 non-null   str
 15  suspect_last_name   5050 non-null   str
 16  suspect_age         5050 non-null   float64
 17  suspect_gender      5050 non-null   str
 18  suspect_race        5050 non-null   str
 19  victim_id           5050 non-null   str
 20  victim_first_name   5050 non-null   str
 21  victim_last_name    5050 non-null   str
 22  victim_age          5050 non-null   float64
 23  victim_gender       5050 non-null   str
 24  victim_phone        5050 non-null   str
 25  weapon_used         5050 non-null   str
 26  severity            5050 non-null   str
 27  case_status         5050 non-null   str
 28  resolution          5050 non-null   str
 29  num_arrests         5050 non-null   float64
 30  property_loss_usd   5050 non-null   float64
 31  reported_online     5050 non-null   str
 32  notes               5050 non-null   str
dtypes: datetime64[us](1), float64(7), str(25)
memory usage: 1.3 MB
None

In [80]:
# รันโค้ดนี้หลังจากที่ทำการโหลด df ใหม่เรียบร้อยแล้ว
df['victim_age_group'] = pd.cut(df['victim_age'], bins=[0, 12, 17, 24, 34, 49, 64, float('inf')], labels=['0-12', '13-17', '18-24', '25-34', '35-49', '50-64', '65+'])
df['suspect_age_group'] = pd.cut(df['suspect_age'], bins=[0, 12, 17, 24, 34, 49, 64, float('inf')], labels=['0-12', '13-17', '18-24', '25-34', '35-49', '50-64', '65+'])

# ทดลองแสดงผลตรวจสอบ 5 แถวแรก
display(df[['victim_age', 'victim_age_group', 'suspect_age', 'suspect_age_group']].head())

   victim_age victim_age_group  suspect_age suspect_age_group
0        51.0            50-64         51.0             50-64
1       231.0              65+         28.0             25-34
2        29.0            25-34         19.0             18-24
3       243.0              65+        262.0               65+
4        51.0            50-64         75.0               65+

In [81]:
#IQR
Q1 = df['victim_age'].quantile(0.25)
Q3 = df['victim_age'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df = df[(df['victim_age'] >= lower) & (df['victim_age'] <= upper)]
df = df[(df['suspect_age'] >= lower) & (df['suspect_age'] <= upper)]

In [82]:
print((df['victim_age'] > 100).sum(),(df['suspect_age'] > 100).sum())
display(df[df['victim_age'] > 100]['victim_age'])
display(df[['victim_age','suspect_age']].describe())
print(df.info())

0 0

Series([], Name: victim_age, dtype: float64)

        victim_age  suspect_age
count  4723.000000  4723.000000
mean     49.944092    46.075069
std      22.024419    15.534113
min      10.000000    15.000000
25%      32.000000    35.000000
50%      52.228039    48.560030
75%      67.000000    56.000000
max      90.000000    75.000000

<class 'pandas.DataFrame'>
Index: 4723 entries, 0 to 5249
Data columns (total 35 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         4723 non-null   str
 1   crime_type          4723 non-null   str
 2   district            4723 non-null   str
 3   city                4723 non-null   str
 4   state               4723 non-null   str
 5   address             4723 non-null   str
 6   latitude            4723 non-null   float64
 7   longitude           4723 non-null   float64
 8   incident_datetime   4723 non-null   datetime64[us]
 9   officer_id          4723 non-null   str
 10  officer_first_name  4723 non-null   str
 11  officer_last_name   4723 non-null   str
 12  badge_number        4723 non-null   float64
 13  suspect_id          4723 non-null   str
 14  suspect_first_name  4723 non-null   str
 15  suspect_last_name   4723 non-null   str
 16  suspect_age         4723 non-null   float64
 17  suspect_gender      4723 non-null   str
 18  suspect_race        4723 non-null   str
 19  victim_id           4723 non-null   str
 20  victim_first_name   4723 non-null   str
 21  victim_last_name    4723 non-null   str
 22  victim_age          4723 non-null   float64
 23  victim_gender       4723 non-null   str
 24  victim_phone        4723 non-null   str
 25  weapon_used         4723 non-null   str
 26  severity            4723 non-null   str
 27  case_status         4723 non-null   str
 28  resolution          4723 non-null   str
 29  num_arrests         4723 non-null   float64
 30  property_loss_usd   4723 non-null   float64
 31  reported_online     4723 non-null   str
 32  notes               4723 non-null   str
 33  victim_age_group    4723 non-null   category
 34  suspect_age_group   4723 non-null   category
dtypes: category(2), datetime64[us](1), float64(7), str(25)
memory usage: 1.2 MB
None

In [83]:
#Export to CSV file
df.to_csv('cleaned_crime_incidents.csv', index=False)