In [125]:
#Import Pandas Library
import pandas as pd

#Import CSV file
df = pd.read_csv('crime_incidents.csv')

print('\n จำนวนแถวและคอลัมน์ของ DataFrame:')
print(df.shape)
print('\n ชนิดข้อมูลและจำนวนค่าที่ไม่ใช่ค่า null ของแต่ละคอลัมน์:')
print(df.info())
print('\n ข้อมูลที่ซ้ำกัน:')
print(df.duplicated().sum())
print('\n ตัวอย่างข้อมูล 5 แถวแรกของ DataFrame:')
display(df.sample(5))

 จำนวนแถวและคอลัมน์ของ DataFrame:
(5250, 33)

 ชนิดข้อมูลและจำนวนค่าที่ไม่ใช่ค่า null ของแต่ละคอลัมน์:
<class 'pandas.DataFrame'>
RangeIndex: 5250 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5250 non-null   str
 1   crime_type          5250 non-null   str
 2   district            5250 non-null   str
 3   city                5250 non-null   str
 4   state               5250 non-null   str
 5   address             5250 non-null   str
 6   latitude            4992 non-null   float64
 7   longitude           4961 non-null   float64
 8   incident_datetime   4910 non-null   str
 9   officer_id          5250 non-null   str
 10  officer_first_name  5250 non-null   str
 11  officer_last_name   5250 non-null   str
 12  badge_number        4938 non-null   float64
 13  suspect_id          4440 non-null   str
 14  suspect_first_name  4440 non-null   str
 15  suspect_last_name   4440 non-null   str
 16  suspect_age         4153 non-null   float64
 17  suspect_gender      3837 non-null   str
 18  suspect_race        3649 non-null   str
 19  victim_id           4993 non-null   str
 20  victim_first_name   4993 non-null   str
 21  victim_last_name    4993 non-null   str
 22  victim_age          4688 non-null   float64
 23  victim_gender       4250 non-null   str
 24  victim_phone        4194 non-null   str
 25  weapon_used         4280 non-null   str
 26  severity            4895 non-null   str
 27  case_status         4519 non-null   str
 28  resolution          4299 non-null   str
 29  num_arrests         4917 non-null   float64
 30  property_loss_usd   4814 non-null   str
 31  reported_online     4746 non-null   str
 32  notes               4181 non-null   str
dtypes: float64(6), str(27)
memory usage: 1.3 MB
None

 ข้อมูลที่ซ้ำกัน:
200

 ตัวอย่างข้อมูล 5 แถวแรกของ DataFrame:

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,officer_first_name,officer_last_name,badge_number,suspect_id,suspect_first_name,suspect_last_name,suspect_age,suspect_gender,suspect_race,victim_id,victim_first_name,victim_last_name,victim_age,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
631,INC003285,arson,Northwest,Springfield,FL,8287 River Rd,32.371246,53.242900,7/10/2020 10:24,OFF0070,Mary,Torres,8534.0,SUS00319,Mary,Scott,-38.0,Other,hispanic,VIC00909,Anthony,Walker,41.0,M,452-967-3226,blunt object,2,Investgation,Arres Made,5.0,4850.55.0,NO,Incident at 8287 River Rd. Officer responded a...
1872,INC004346,Domestic Violence,Northeast,Riverside,AZ,6121 Maple Dr,46.791933,-115.286815,13/9/2023 0:36,OFF0150,Anthony,Davis,8409.0,SUS00169,John,Torres,16.0,Other,White,VIC00656,Matthew,Green,64.0,M,817-384-4555,KNIFE,2,closed,NO ARREST,5.0,NaN,YES,Incident at 6121 Maple Dr. Officer responded a...
4272,INC004877,DUI,NORTH,Riverside,FL,7760 Oak Ave,45.206020,-76.774160,28/11/2024 6:54,OFF0121,Chris,Wright,8912.0,SUS00494,Mark,Jackson,44.0,male,NaN,VIC00009,Chris,Scott,43.0,Male,675-882-2688,KNIFE,Crit,Under Investigation,warning,5.0,6027.71,1,Incident at 7760 Oak Ave. Officer responded at...
1784,INC003906,Scam,East,Springfield,FL,1830 Park Rd,34.594428,-103.557000,11/3/2019 2:57,OFF0026,james,Torres,3621.0,SUS00069,Charles,Harris,NaN,MALE,Unknown,VIC00254,Jennifer,Taylor,25.0,Female,988-745-7772,Pistol,2,OPEN,NO ARREST,0.0,49845.19,NaN,Incident at 1830 Park Rd. Officer responded at...
2534,INC003798,FRAUD,east,Riverside,OH,7735 Lincoln St,25.750776,-121.366194,8/1/2018 5:22,OFF0023,Joseph,Miller,2457.0,NaN,NaN,NaN,NaN,NaN,NaN,VIC00733,Anthony,Nguyen,186.0,F,325-605-4056,Blunt Object,2,Closed,Arres Made,5.0,13174.84,No,NaN

In [126]:
#Check duplicated rows
print(df.duplicated().sum())
print(df.shape)

#Delete duplicated rows
df = df.drop_duplicates()
print(df.shape)

200
(5250, 33)
(5050, 33)

In [127]:
#Change data types
df['incident_datetime'] = pd.to_datetime(df['incident_datetime'],errors='coerce')
df['property_loss_usd'] = pd.to_numeric(df['property_loss_usd'], errors='coerce')
df['victim_age'] = pd.to_numeric(df['victim_age'], errors='coerce')

df.info()

<class 'pandas.DataFrame'>
Index: 5050 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5050 non-null   str
 1   crime_type          5050 non-null   str
 2   district            5050 non-null   str
 3   city                5050 non-null   str
 4   state               5050 non-null   str
 5   address             5050 non-null   str
 6   latitude            4799 non-null   float64
 7   longitude           4772 non-null   float64
 8   incident_datetime   4457 non-null   datetime64[us]
 9   officer_id          5050 non-null   str
 10  officer_first_name  5050 non-null   str
 11  officer_last_name   5050 non-null   str
 12  badge_number        4749 non-null   float64
 13  suspect_id          4275 non-null   str
 14  suspect_first_name  4275 non-null   str
 15  suspect_last_name   4275 non-null   str
 16  suspect_age         3998 non-null   float64
 17  suspect_gender      3698 non-null   str
 18  suspect_race        3525 non-null   str
 19  victim_id           4802 non-null   str
 20  victim_first_name   4802 non-null   str
 21  victim_last_name    4802 non-null   str
 22  victim_age          4508 non-null   float64
 23  victim_gender       4087 non-null   str
 24  victim_phone        4031 non-null   str
 25  weapon_used         4120 non-null   str
 26  severity            4708 non-null   str
 27  case_status         4354 non-null   str
 28  resolution          4138 non-null   str
 29  num_arrests         4726 non-null   float64
 30  property_loss_usd   4500 non-null   float64
 31  reported_online     4564 non-null   str
 32  notes               4022 non-null   str
dtypes: datetime64[us](1), float64(7), str(25)
memory usage: 1.3 MB

C:\Users\bpt7474\AppData\Local\Temp\ipykernel_34740\379047736.py:2: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['incident_datetime'] = pd.to_datetime(df['incident_datetime'],errors='coerce')

In [128]:
# Check and Fill missing values

df = df.fillna({
    'latitude': df['latitude'].mean(),
    'longitude': df['longitude'].mean(),
    'incident_datetime' : df['incident_datetime'].ffill(),
    'badge_number' : df['badge_number'].mean(),
    'suspect_id' : 'unknown',
    'suspect_first_name' : 'unknown',
    'suspect_last_name' : 'unknown',
    'suspect_age' : df['suspect_age'].mean(),
    'suspect_gender' : 'unknown',
    'suspect_race' : 'unknown',
    'victim_id' : 'unknown',
    'victim_first_name' : 'unknown',
    'victim_last_name' : 'unknown',
    'victim_age' : df['victim_age'].mean(),
    'victim_gender' : 'unknown',
    'victim_phone' : 'unknown',
    'weapon_used' : 'unknown',
    'severity' : 'unknown',
    'case_status' : 'unknown',
    'resolution' : 'unknown',
    'num_arrests' : df['num_arrests'].mean(),
    'property_loss_usd' : df['property_loss_usd'].mean(),
    'reported_online' : 'unknown',
    'notes' : 'unknown'
})

print('\n-------------ข้อมูลหลังการเติมข้อมูล-------------')
print(df.isna().sum())

-------------ข้อมูลหลังการเติมข้อมูล-------------
incident_id           0
crime_type            0
district              0
city                  0
state                 0
address               0
latitude              0
longitude             0
incident_datetime     0
officer_id            0
officer_first_name    0
officer_last_name     0
badge_number          0
suspect_id            0
suspect_first_name    0
suspect_last_name     0
suspect_age           0
suspect_gender        0
suspect_race          0
victim_id             0
victim_first_name     0
victim_last_name      0
victim_age            0
victim_gender         0
victim_phone          0
weapon_used           0
severity              0
case_status           0
resolution            0
num_arrests           0
property_loss_usd     0
reported_online       0
notes                 0
dtype: int64

In [129]:
# Change to lower string
pd.set_option('display.max_columns', 35)


column_str = ['crime_type', 'district', 'city', 'suspect_gender', 'suspect_race', 'victim_gender', 'severity', 'resolution','reported_online','case_status','weapon_used']

# ใช้ .apply เพื่อสั่งให้ทุกคอลัมน์ในรายชื่อแปลงเป็นตัวพิมพ์เล็ก
df[column_str] = df[column_str].apply(lambda x: x.str.lower())

In [130]:
df.sample(10)

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,officer_first_name,officer_last_name,badge_number,suspect_id,suspect_first_name,suspect_last_name,suspect_age,suspect_gender,suspect_race,victim_id,victim_first_name,victim_last_name,victim_age,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
163,INC001911,domestc violence,south,springfield,NC,8295 Elm Blvd,41.748432,-103.027068,2019-11-04 07:25:00,OFF0055,Barbara,Davis,7553.0,SUS00347,Michelle,Lee,62.00000,female,hispanic,VIC00013,Patricia,Walker,62.000000,other,880-339-7285,pistol,3,resolved,arrest made,3.0,23107.330000,false,Incident at 8295 Elm Blvd. Officer responded a...
1088,INC003507,trespassing,west,riverside,CA,5384 Oak Ave,29.203936,-98.553161,2019-05-04 23:04:00,OFF0058,Sarah,Thompson,2824.0,SUS00716,Michael,Thompson,48.56003,male,black,VIC00335,Michael,Miller,67.000000,female,448-743-6160,firearm,unknown,closed,warning issued,4.0,13587.200000,1,Incident at 5384 Oak Ave. Officer responded at...
2560,INC003195,fraud,southeast,springfield,CA,2629 River Rd,47.871759,-88.751699,2023-08-21 19:35:00,OFF0084,Carol,Lee,8126.0,SUS00720,Charles,Johnson,20.00000,male,white,VIC00953,Susan,Anderson,52.228039,other,863-340-9636,rifle,3,closed,no arrest,1.0,46565.950000,no,unknown
3289,INC000185,trespassing,midtown,maplewood,GA,2023 Cedar Lane,47.927518,-85.260842,2022-01-25 23:20:00,OFF0056,Sarah,Moore,7171.0,SUS00061,David,Jones,67.00000,unknown,asian,VIC00869,Donna,Davis,16.000000,f,994-283-8987,bat,low,pendng,unknown,1.0,49553.160000,true,Incident at 2023 Cedar Lane. Officer responded...
1413,INC003676,cybercrime,west,springfield,CA,3434 Maple Dr,177.370800,-89.665793,2019-07-14 07:25:00,OFF0030,MARY,Johnson,1316.0,SUS00295,David,Jones,44.00000,male,black,VIC00161,Susan,Nguyen,27.000000,m,562-874-3071,hands,2,resolved,arrest made,4.0,26714.220000,yes,Incident at 3434 Maple Dr. Officer responded a...
1394,INC004585,arsen,nor,fairview,FL,3135 Maple Dr,35.916657,-83.445673,2019-02-11 00:22:00,OFF0065,Patricia,Wright,6699.0,SUS00631,Karen,Hall,39.00000,f,hispanic,VIC00051,John,Brown,64.000000,male,unknown,unarmed,high,open,case dismissed,0.0,13998.010000,yes,Incident at 3135 Maple Dr. Officer responded a...
2978,INC004143,murder,west,fairview,TX,2562 Maple Dr,29.806660,-113.984658,2019-11-08 14:20:00,OFF0137,Jessica,Anderson,3022.0,SUS00399,Charles,Torres,28.00000,other,unknown,VIC00276,Barbara,Young,22.000000,male,unknown,unknown,high,resolved,arrest made,1.0,8436.340000,false,unknown
1775,INC002561,kidnapping,nor,fairview,CA,1142 Washington Ave,39.706533,-93.588194,2022-02-03 02:33:00,OFF0022,Matthew,Green,3234.0,SUS00106,Donna,Torres,33.00000,other,other,VIC00277,Emily,Smith,57.000000,male,216-243-4604,unarmed,3,closed,no arrest,1.0,2864.720000,no,Incident at 1142 Washington Ave. Officer respo...
4651,INC000641,vandalism,west,hillcrest,AZ,2888 Sunset Blvd,26.550333,-100.479469,2023-07-09 10:35:00,OFF0042,Barbara,Moore,8480.0,SUS00361,Michelle,Williams,66.00000,m,black,VIC00134,Michael,Thompson,11.000000,male,757-967-4047,unarmed,med,investgation,arrest made,3.0,22774.688522,no,Incident at 2888 Sunset Blvd. Officer responde...
320,INC004931,theft,west,fairview,FL,5472 Elm Blvd,31.379031,-105.796824,2020-06-02 08:34:00,OFF0138,Barbara,Garcia,7129.0,SUS00211,Michelle,Moore,74.00000,f,unknown,VIC00952,Patricia,Walker,77.000000,other,unknown,rifle,low,closed,arrest made,0.0,29481.590000,unknown,Incident at 5472 Elm Blvd. Officer responded a...

In [131]:
#Change word
# ใช้ .replace() ตรงๆ โดยไม่ต้องใส่ .str และเพิ่ม regex=False เพื่อความแม่นยำ
df['district'] = df['district'].str.strip()
df['district'] = df['district'].replace({'nor':'north','sou':'south', 'cen' : 'central','eas':'east', 'mid' : 'midtown', 'wes' : 'west'})
df['suspect_gender'] = df['suspect_gender'].replace({'m':'male', 'f':'female'}, regex=False)
df['severity'] = df['severity'].replace({'med':'medium','crit':'critical','1':'low', '2':'medium','3':'high', '4':'critical'}, regex=False)
df['case_status'] = df['case_status'].replace({'pendng':'pending','under investigation' : 'investigation','investgation':'investigation'}, regex=False)
df['reported_online'] = df['reported_online'].replace({'true':'yes','false':'no', '1':'yes', '0':'no'}, regex=False)
df['resolution'] = df['resolution'].replace({'case dismissed' : 'dismissed', 'arres made' : 'arrested','arrest made':'arrested', 'warning' : 'warning issued'}, regex=False)
df['victim_gender'] = df['victim_gender'].replace({'m':'male', 'f':'female'}, regex=False)

In [132]:
df.sample(10)

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,officer_first_name,officer_last_name,badge_number,suspect_id,suspect_first_name,suspect_last_name,suspect_age,suspect_gender,suspect_race,victim_id,victim_first_name,victim_last_name,victim_age,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
3804,INC004942,arson,south,riverside,OH,6938 Cedar Lane,29.575865,-94.434172,2023-09-23 14:47:00,OFF0110,Sarah,Harris,2661.000000,SUS00568,Linda,Brown,28.00000,female,unknown,VIC00381,Anthony,Hill,70.000000,unknown,874-238-5770,rifle,low,unknown,dismissed,-2.000000,22017.48,yes,Incident at 6938 Cedar Lane. Officer responded...
4718,INC004005,fraud,south,fairview,PA,7900 Lincoln St,34.281579,-105.856601,2023-05-04 19:21:00,OFF0070,Jessica,Jones,5554.343441,SUS00564,Mark,Taylor,22.00000,unknown,white,VIC00262,Michael,Wilson,11.000000,female,410-637-3369,blunt object,high,open,no arrest,2.000000,8844.69,no,Incident at 7900 Lincoln St. Officer responded...
982,INC002797,homicide,north,lakewood,IL,1657 Washington Ave,46.665053,-109.024918,2020-02-09 13:39:00,OFF0018,Jennifer,Miller,9991.000000,SUS00623,Nancy,Hall,22.00000,male,white,VIC00131,Patricia,Anderson,80.000000,male,543-727-7521,firearm,unknown,unknown,no arrest,2.264706,17444.37,unknown,Incident at 1657 Washington Ave. Officer respo...
4273,INC003939,theft/larceny,northwest,centerville,FL,486 Elm Blvd,42.266202,-93.347667,2022-03-07 22:06:00,OFF0090,Emily,Allen,5615.000000,SUS00245,Sarah,Harris,-35.00000,unknown,unknown,VIC00504,Mark,Smith,80.000000,unknown,849-470-3391,rifle,critical,investigation,unknown,4.000000,29586.89,no,unknown
1215,INC000218,drug offence,midtown,riverside,IL,8509 Main St,28.401709,-100.663415,2019-11-16 07:26:00,OFF0037,Susan,Harris,1506.000000,SUS00251,Daniel,Jackson,48.56003,male,unknown,VIC00092,Richard,Walker,23.000000,female,841-795-9927,unknown,critical,investigation,warning issued,2.000000,45516.37,no,Incident at 8509 Main St. Officer responded at...
3596,INC003807,murder,midtown,oakdale,TX,6931 Elm Blvd,40.873266,-118.250693,2018-10-14 12:20:00,OFF0112,Richard,Jones,3391.000000,SUS00100,Karen,Scott,41.00000,female,unknown,VIC00106,Anthony,Miller,70.000000,female,368-439-8083,gun,low,resolved,unknown,3.000000,33401.56,no,Incident at 6931 Elm Blvd. Officer responded a...
4676,INC003289,roberry,east,oakdale,NY,4165 Main St,26.568293,-74.385811,2022-06-23 09:14:00,OFF0068,Richard,Taylor,9140.000000,SUS00785,Linda,Jackson,40.00000,female,asian,VIC00749,John,Allen,64.000000,unknown,420-144-3330,gun,high,closed,arrested,2.000000,47319.14,no,Incident at 4165 Main St. Officer responded at...
1571,INC001186,trespassing,midtown,centerville,NY,2264 Elm Blvd,39.769308,-115.074967,2022-02-03 08:11:00,OFF0135,Mary,Lee,3347.000000,SUS00535,Donna,Allen,57.00000,unknown,asian,VIC00406,Charles,Brown,90.000000,male,629-282-1511,hands,high,pending,warning issued,4.000000,20737.11,no,Incident at 2264 Elm Blvd. Officer responded a...
4085,INC003764,sexual assault,south,lakewood,AZ,6080 Main St,44.013618,-119.351072,2018-02-11 04:34:00,OFF0145,Matthew,Miller,1436.000000,SUS00302,Jessica,Taylor,32.00000,unknown,unknown,VIC00422,Michelle,Torres,52.228039,female,398-477-8786,hands,low,unknown,dismissed,4.000000,36709.67,no,Incident at 6080 Main St. Officer responded at...
4543,INC001680,trespassing,northwest,lakewood,NC,7211 Washington Ave,43.894163,-77.233360,2021-11-28 22:38:00,OFF0098,Karen,Allen,3448.000000,SUS00300,Chris,Moore,47.00000,female,white,VIC00089,Mark,Garcia,-64.000000,male,unknown,gun,low,investigation,unknown,-2.000000,8649.67,yes,Incident at 7211 Washington Ave. Officer respo...

In [133]:
print((df['victim_age']<0).sum())
print((df['suspect_age']<0).sum())

214
167

In [134]:
# Change negative values to positive
df['victim_age'] = df['victim_age'].abs()
df['suspect_age'] = df['suspect_age'].abs()
df['property_loss_usd'] = df['property_loss_usd'].abs()

print((df['victim_age']<0).sum())
print((df['suspect_age']<0).sum())
print(df.info())

0
0
<class 'pandas.DataFrame'>
Index: 5050 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5050 non-null   str
 1   crime_type          5050 non-null   str
 2   district            5050 non-null   str
 3   city                5050 non-null   str
 4   state               5050 non-null   str
 5   address             5050 non-null   str
 6   latitude            5050 non-null   float64
 7   longitude           5050 non-null   float64
 8   incident_datetime   5050 non-null   datetime64[us]
 9   officer_id          5050 non-null   str
 10  officer_first_name  5050 non-null   str
 11  officer_last_name   5050 non-null   str
 12  badge_number        5050 non-null   float64
 13  suspect_id          5050 non-null   str
 14  suspect_first_name  5050 non-null   str
 15  suspect_last_name   5050 non-null   str
 16  suspect_age         5050 non-null   float64
 17  suspect_gender      5050 non-null   str
 18  suspect_race        5050 non-null   str
 19  victim_id           5050 non-null   str
 20  victim_first_name   5050 non-null   str
 21  victim_last_name    5050 non-null   str
 22  victim_age          5050 non-null   float64
 23  victim_gender       5050 non-null   str
 24  victim_phone        5050 non-null   str
 25  weapon_used         5050 non-null   str
 26  severity            5050 non-null   str
 27  case_status         5050 non-null   str
 28  resolution          5050 non-null   str
 29  num_arrests         5050 non-null   float64
 30  property_loss_usd   5050 non-null   float64
 31  reported_online     5050 non-null   str
 32  notes               5050 non-null   str
dtypes: datetime64[us](1), float64(7), str(25)
memory usage: 1.3 MB
None

In [ ]:
#Add age group column
df['victim_age_group'] = pd.cut(df['victim_age'], bins=[0, 12, 17, 24, 34, 49, 64, 100], labels=['0-12', '13-17', '18-24', '25-34', '35-49', '50-64', '65+'])
df['suspect_age_group'] = pd.cut(df['suspect_age'], bins=[0, 12, 17, 24, 34, 49, 64, 100], labels=['0-12', '13-17', '18-24', '25-34', '35-49', '50-64', '65+'])

In [135]:
#Export to CSV file
df.to_csv('cleaned_crime_incidents.csv', index=False)